### ISSUE TITLE
delete_network() function fails against Pureport Prod api - invalid return code

### ISSUE THREAD

**Issue by rghodgkin** [pureport/pureport-python#29]
When executing a 'session.delete_network(<net_id>)' against the Pureport public api ('https://api.pureport.com'), this seems to throw a Pureport exception stating "pureport.exceptions.PureportError: invalid status code received from response".    The reason seems to be that the DELETE was successful on Pureport side but is returning a "204" response rather than expected "200".  

If I manually update the 'DELETE' status_codes list to include '204' it works cleanly.

-----------------------------------------------
Response from Pureport API for network delete:
    Request URL: https://api.pureport.com/networks/network-PoZdpa9GRAoXkp5luGrFrg
    Request Method: DELETE
    Status Code: 204 
    Remote Address: 34.231.19.164:443
    Referrer Policy: no-referrer-when-downgrade

**Comment by privateip** [comment]
This should be fixed in #31 ... can you pull down the latest devel and confirm?

**Comment by rghodgkin** [comment]
Re-tested against latest on 09/22/2020 - fixed.
