### ISSUE TITLE
gateway_respawn() function fails against Pureport Prod api - invalid return code

### ISSUE THREAD

**Issue by rghodgkin** [pureport/pureport-python#32]
When executing any of the following three functions below against the Pureport API, the action succeeds, but the response generates a pureport.Exception for invalid status code.    The three functions below are returning a "200" response and expected for a POST looks to be "201".
Functions:   stop_gateway(), start_gateway(), respawn_gateway()

Output:
(Pdb) runtime.session.start_gateway(gw_id)
*** pureport.exceptions.PureportError: invalid status code received from response
(Pdb) result = runtime.session.get_connection(conn_id).serialize()

**Comment by privateip** [comment]
This error should be fixed in #33.

**Comment by rghodgkin** [comment]
Retested with latest as of 09/22/2020 - fixed.
